import React from 'react'

function Home() {
  return (
    <div>
      <div className="container">
        <section>
          <div className="row" style={{marginBottom:'80px'}}>
            <div className="col-6 mt-5"><img src="https://res.cloudinary.com/akeem/image/upload/v1657707461/maize-prefered-696x392-1_yesb1j.jpg" alt="" width={'100%'}/></div>
            <div className="col-6 mt-5">
              <p style={{fontSize:'18px'}}>As the world population continues to grow, much more effort and innovation will be urgently needed in order to sustainably increase agricultural production, improve the global supply chain, decrease food losses and waste, and ensure that all who are suffering from hunger and malnutrition have access to nutritious food</p>
              <p style={{fontSize:'18px'}}>At Agriverse, we believe that it is possible to eradicate hunger within the next generation, and also greatly improve the local supply chain of some selected agricultural produce, and globally too, invariably, and are working to achieve this goal.</p>
              <p style={{fontSize:'18px'}}>The slected agricultural produce we are into are; Cocoa beans, Coconut, Cashew nuts, Cassava, Ginger, Maize, Oil Palm fruit, Plantain, Sesame, Soya, and Yam.</p>
            </div>
          </div>
        </section>

        <section>
          <div className="row" style={{marginBottom:'80px'}}>
            <h2 style={{marginBottom:'40px', textAlign:'center'}}>What We Do</h2>
            <div className="col-6">
              <p style={{fontSize:'18px'}}>Poor storage facilities in farms lead to pest infestations and mould ruining crops. Lack of access to technology and markets means many farmers are forced to watch their crops rot in fields as the labour and financial investment required to harvest them and also get them to the market is often unavailable.</p>
              <p style={{fontSize:'18px'}}>Agriverse provide an array of multiverses; we link the farmer multiverse to the market place multiverse, and to the enhanced produvtivity multiverse as well.</p>
              <p style={{fontSize:'18px'}}>At Agriverse, all we simply do is to go to the farms of farmers who are registered with us, and make sure all their harvested farm produce get to the market by purchasing it off them and taking them directly to the exporters or companies who are registered with us as well and in need of these farm produce.</p>
              <p style={{fontSize:'18px'}}>Agriculture systems in Nigeria must become more productive and less wasteful. Sustainable agricultural practices and food systems, including both production and consumption, must be pursued from a holistic and integrated perspective... we provide this holistic and integrated perspectuve at Agriverse</p>
              <p style={{fontSize:'18px'}}>Because quality is our watchword at Agriverse and we take it very seriously, we also provide quarterly seminars and trainings to our registered farmers where we educate and show them how to greatly increase the quality of their harvests, as well as productivity too by giving them easy access to the best seedlings and improved species.</p>
            </div>
            <div className="col-6 mb-5"><img src="https://res.cloudinary.com/akeem/image/upload/v1657707411/1536x1536_gettyimages-1220162136_pxastc.jpg" alt="" width={'100%'} height={'100%'}/></div>
          </div>
        </section>

        <section>
          <div className="row">
          <h2 style={{marginBottom:'40px', textAlign:'center'}}>Our Vision</h2>
          <div className="col-6"><img src="https://res.cloudinary.com/akeem/image/upload/v1657707535/cocoa-farm_w1e0xm.jpg" alt="" width={'100%'} height={'75%'}/></div>
            <div className="col-6">
              <p style={{fontSize:'18px'}}>Agriculture is a proven engine for poverty reduction. GDP growth generated by agriculture is more effective in reducing poverty than growth in any other sector. In sub-Saharan Africa, growth in agriculture reduces poverty up to 11 times faster than growth in other sectors.</p>
              <p style={{fontSize:'18px'}}>Our vision is to triple the the agricultural productivity and incomes of all farmers, in particular women who are registered with us and become the leading supplier of quality farm produce in the country.</p>
            </div>
          </div>
        </section>
      </div>
    </div>
  )
}

export default Home